### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Aculoss** [arnokeesman/Magnet-Command#1]
Have a configurable range and also make the items no clip.

**Comment by arnokeesman** [comment]
With "no clip" do you mean that the items can pass through blocks?

Op di 8 aug. 2023 10:17 schreef Aculos ***@***.***>:

**Comment by Aculoss** [comment]
yes exactly that!

**Comment by arnokeesman** [comment]
I'll have to look into that, just disabling clipping in my mind will just make it fall through the ground.
Did you encounter cases where it got stuck on a corner or are you actually looking to just magnet through blocks?

**Comment by Aculoss** [comment]
no issues getting stuck just thought it would be smoother and more effiecient

**Comment by Aculoss** [comment]
great mod btw!

**Comment by arnokeesman** [comment]
During the initial development of the mod different modes were discussed
We had Inject, Teleport and Pull. Inject currently being in use by OnBreak and Pull by Range
Creating a config now anyway so will make the Teleport mode available to both OnBreak and Range
Hope setting Range to Teleport will satisfy the no-clip behavior until I can find a proper way to implement it
A TeleportSteps mode might get added as something in between, Teleport will just teleport the items directly to the player

**Comment by Aculoss** [comment]
You are a legend my friend

**Comment by Aculoss** [comment]
I edited the integer to 8 for the time being

**Comment by arnokeesman** [comment]
Config is now live and documentation(readme and mod page) has been updated
