### ISSUE TITLE
Shulkerbox drops inventory when you hit it with pickaxe.

### ISSUE THREAD

**Issue by asundrus** [arnokeesman/Magnet-Command#2]
When you have a shulkerbox with items in it, place it on the ground, and use pickaxe on it, the shulker drops it's inventory after being hit with the pickaxe.

**Comment by arnokeesman** [comment]
that doesn't sound good, I´ll look into excluding inventories that should retain their content

**Comment by arnokeesman** [comment]
what version do you need it for? 
should be able to fix 1 version today, the others I'll do tomorrow and do and publish to MR

**Comment by asundrus** [comment]
Sorry, forgot to mention version, I'm running Fabric 1.20.2.

**Comment by arnokeesman** [comment]
in a couple minutes an "Artifacts" button appears at the bottom here, click that, then grab the fixed jar from inside that zip, have fun
will close this issues when it's all backported and released

**Comment by arnokeesman** [comment]
oh wow, it's called Magnet-Command-24 (24 as in build number)
you can grab it with [this link](https://github.com/arnokeesman/Magnet-Command/suites/17854797188/artifacts/1024459671) directly (still have to get the jar out of the zip)

**Comment by asundrus** [comment]
Thanks for the quick response and update, it works just fine now.
