### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Aculoss** [arnokeesman/Magnet-Command#3]
Could you adjust the pullStrength to be higher/quicker? And make it pull items before they fall?

**Comment by arnokeesman** [comment]
I can add config options for these yeah
pulling before they fall might be somewhat of a mess in some modes so it'll be disabled by default in config

**Comment by Aculoss** [comment]
ok thankyou!

**Comment by arnokeesman** [comment]
build are available in the action artifacts (if you don't know, google does)
mod jar can be found in that zip
grab the run from 1.20.1 for 20.1 and 20.2
grab from master for 20.3 and 20.4
will do 19 and 18 + official releases tomorrow if all works out

**Comment by Aculoss** [comment]
thank you very much

**Comment by Aculoss** [comment]
Would you also be able to change the time in ticks to be less, so it tries to pick up an item before it starts falling or touches a block

**Comment by arnokeesman** [comment]
welp, took a bit longer than expected to find time to release, but released on all supported versions now

**Comment by Aculoss** [comment]
thankyou, your a legend 
:)
