### ISSUE TITLE
skulk dosnt drop xp with /magnet onbreak

### ISSUE THREAD

**Issue by Jarrose37** [arnokeesman/Magnet-Command#4]
when using the magnet and breaking skulk to repair tools or get xp when using magnet onbreak it does not drop xp for some reason

**Comment by arnokeesman** [comment]
Hmm, might have to look into that
Are you sure this is not the intended behaviour for silk touch?

Op wo 20 mrt. 2024 01:22 schreef Jarrose37 ***@***.***>:

**Comment by Vaskyy** [comment]
What does this have to do with silk touch @arnokeesman?

Have the same behavior when fortune breaking normal ores.
When items get picked up on break no xP gets generated ever.

**Comment by arnokeesman** [comment]
without details, assumptions are made
this seems like a problem yeah, I'll what I can do

**Comment by arnokeesman** [comment]
Thanks for the report, should be fixed in latest, you can grab it from Actions or Modrinth
Enjoy the mod and if you find anything else, do let me know!
