### ISSUE TITLE
Magnet OnBreak does not give Decorated Pot loot on 1.21

### ISSUE THREAD

**Issue by Jarrose37** [arnokeesman/Magnet-Command#5]
When in the new trials and you break a pot loot drops but with this mod OnBreak loot just gets deleted and you get the pot

**Comment by Vaskyy** [comment]
Can confirm that.
U get the pot mats, but not the loot.

**Comment by arnokeesman** [comment]
Interesting, does the same problem occur with opts placed by players? (I haven't touched pots or tails chambers yet)
Will look into it tomorrow, way too late to dig into code now

**Comment by Jarrose37** [comment]
https://streamable.com/pwymzl if ur inv is full it will delete the items in the pot

**Comment by arnokeesman** [comment]
ah thanks for the clarification, this probably isn't limited to pots then....

**Comment by arnokeesman** [comment]
following the code, I really don't have a clue what happening, its fine for other containers and everything
in my limited testing this fix seems to be fine for both pots and other containers though
https://github.com/arnokeesman/Magnet-Command/actions/runs/9943600796

**Comment by arnokeesman** [comment]
released in 0.2.5
